/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package csdlpt;

import java.awt.CardLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author 123de
 */
public class AdminDashboardFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboardFrame
     */
    
    private String userToken; 
    private final String API_BASE_URL = "http://127.0.0.1:9999";
    
    public AdminDashboardFrame() {
        initComponents();
    }
    
   public AdminDashboardFrame(String token) {
        this.userToken = token;
        initComponents();
        
        // Gọi các hàm khởi tạo logic (bạn sẽ copy vào sau)
        initCustomLogic(); 
        
        // Mặc định vào trang Dashboard
        switchScreen("Dashboard");
        loadDashboardData();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        sidebarPanel = new javax.swing.JPanel();
        btnTongQuan = new javax.swing.JButton();
        btnQuanLyNhanVien = new javax.swing.JButton();
        btnTruyVan = new javax.swing.JButton();
        btnQuanLyChiNhanh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        queryPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtMNV = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMKH = new javax.swing.JTextField();
        btnCau1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblQuerry = new javax.swing.JTable();
        branchManagementPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnSearrch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnAddBranch = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBranchs = new javax.swing.JTable();
        dashboardScreenPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDashboardReport = new javax.swing.JTable();
        staffManagementPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtSearchSaff = new javax.swing.JTextField();
        btnAdddSaff = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSaffs = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.BorderLayout());

        btnTongQuan.setText("Tổng Quan");
        btnTongQuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTongQuanActionPerformed(evt);
            }
        });

        btnQuanLyNhanVien.setText("Nhân Viên");
        btnQuanLyNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyNhanVienActionPerformed(evt);
            }
        });

        btnTruyVan.setText("TruyVan");
        btnTruyVan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTruyVanActionPerformed(evt);
            }
        });

        btnQuanLyChiNhanh.setText("Chi Nhánh");
        btnQuanLyChiNhanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyChiNhanhActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        jLabel1.setText("MENU");

        jLabel8.setText("ADMIN");

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQuanLyChiNhanh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTongQuan, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(btnQuanLyNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTruyVan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(3, 3, 3)
                .addComponent(btnTongQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnQuanLyChiNhanh, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnQuanLyNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTruyVan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contentPanel.setLayout(new java.awt.CardLayout());

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel5.setText("Câu 1");

        jLabel6.setText("Mã Nhân Viên :");

        jLabel7.setText("Mã Khách Hàng :");

        btnCau1.setText("Tìm Kiếm");

        tblQuerry.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblQuerry);

        javax.swing.GroupLayout queryPanelLayout = new javax.swing.GroupLayout(queryPanel);
        queryPanel.setLayout(queryPanelLayout);
        queryPanelLayout.setHorizontalGroup(
            queryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(queryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(queryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(queryPanelLayout.createSequentialGroup()
                        .addGroup(queryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(queryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(queryPanelLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(queryPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(queryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMKH, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                    .addComponent(txtMNV))))
                        .addGap(0, 97, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, queryPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(queryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCau1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE))))
                .addContainerGap())
        );
        queryPanelLayout.setVerticalGroup(
            queryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(queryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(queryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMNV, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(queryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtMKH, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCau1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contentPanel.add(queryPanel, "Querry");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel3.setText("Chi Nhánh");

        btnSearrch.setText("Tìm Kiếm");

        btnAddBranch.setText("Thêm CN");

        tblBranchs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblBranchs);

        javax.swing.GroupLayout branchManagementPanelLayout = new javax.swing.GroupLayout(branchManagementPanel);
        branchManagementPanel.setLayout(branchManagementPanelLayout);
        branchManagementPanelLayout.setHorizontalGroup(
            branchManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(branchManagementPanelLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, branchManagementPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txtSearch)
                .addGap(18, 18, 18)
                .addComponent(btnSearrch)
                .addGap(18, 18, 18)
                .addComponent(btnAddBranch)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, branchManagementPanelLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        branchManagementPanelLayout.setVerticalGroup(
            branchManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(branchManagementPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(branchManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(branchManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSearrch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddBranch))
                    .addComponent(txtSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        contentPanel.add(branchManagementPanel, "QuanLyChiNhanh");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel2.setText("Tổng Quan ");

        tblDashboardReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDashboardReport);

        javax.swing.GroupLayout dashboardScreenPanelLayout = new javax.swing.GroupLayout(dashboardScreenPanel);
        dashboardScreenPanel.setLayout(dashboardScreenPanelLayout);
        dashboardScreenPanelLayout.setHorizontalGroup(
            dashboardScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardScreenPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(125, 125, 125))
            .addGroup(dashboardScreenPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        dashboardScreenPanelLayout.setVerticalGroup(
            dashboardScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardScreenPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        contentPanel.add(dashboardScreenPanel, "Dashboard");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel4.setText("Nhân Viên");

        txtSearchSaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchSaffActionPerformed(evt);
            }
        });

        btnAdddSaff.setText("Tìm Kiếm");

        jButton1.setText("Thêm Nhân Viên");

        tblSaffs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblSaffs);

        javax.swing.GroupLayout staffManagementPanelLayout = new javax.swing.GroupLayout(staffManagementPanel);
        staffManagementPanel.setLayout(staffManagementPanelLayout);
        staffManagementPanelLayout.setHorizontalGroup(
            staffManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffManagementPanelLayout.createSequentialGroup()
                .addGroup(staffManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(staffManagementPanelLayout.createSequentialGroup()
                        .addGroup(staffManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(staffManagementPanelLayout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(staffManagementPanelLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(txtSearchSaff, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAdddSaff)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, staffManagementPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        staffManagementPanelLayout.setVerticalGroup(
            staffManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffManagementPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(staffManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchSaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdddSaff)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        contentPanel.add(staffManagementPanel, "QuanLyNhanVien");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTongQuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTongQuanActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(contentPanel.getLayout());
    cl.show(contentPanel, "Dashboard"); 
    }//GEN-LAST:event_btnTongQuanActionPerformed

    private void btnQuanLyNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyNhanVienActionPerformed
        // TODO add your handling code here:
         CardLayout cl = (CardLayout)(contentPanel.getLayout());
    cl.show(contentPanel, "QuanLyNhanVien"); 
    
    }//GEN-LAST:event_btnQuanLyNhanVienActionPerformed

    private void btnQuanLyChiNhanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyChiNhanhActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(contentPanel.getLayout());
    cl.show(contentPanel, "QuanLyChiNhanh"); // "QuanLyChiNhanh" là tên Card Name bạn đã đặt
    // Gọi hàm để tải dữ liệu cho bảng chi nhánh
    }//GEN-LAST:event_btnQuanLyChiNhanhActionPerformed

    private void btnTruyVanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTruyVanActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(contentPanel.getLayout());
    cl.show(contentPanel, "Querry"); 
    }//GEN-LAST:event_btnTruyVanActionPerformed

    private void txtSearchSaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchSaffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchSaffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboardFrame().setVisible(true);
            }
        });
    }
    
    
    
    
    // ==============================================================
    // PHẦN 1: CÁC HÀM HELPER (GỬI API, XỬ LÝ JSON, MENU CHUỘT PHẢI)
    // ==============================================================

    // 1. Hàm Gửi Request tới Node.js (GET, POST, PUT, DELETE)
    private String sendRequest(String endpoint, String method, String jsonInput) {
        try {
            URL url = new URL(API_BASE_URL + endpoint);
            HttpURLConnection conn = (HttpURLConnection) url.openConnection();
            conn.setRequestMethod(method);
            conn.setRequestProperty("Content-Type", "application/json");
            // Gửi Token đi để Server xác thực
            if (userToken != null) {
                conn.setRequestProperty("Authorization", userToken); 
            }
            conn.setDoOutput(true);

            // Gửi dữ liệu JSON (nếu có)
            if (jsonInput != null && !jsonInput.isEmpty()) {
                try (OutputStream os = conn.getOutputStream()) {
                    byte[] input = jsonInput.getBytes(StandardCharsets.UTF_8);
                    os.write(input, 0, input.length);
                }
            }

            // Nhận kết quả trả về
            int code = conn.getResponseCode();
            InputStreamReader reader = (code >= 200 && code < 300) 
                    ? new InputStreamReader(conn.getInputStream(), StandardCharsets.UTF_8)
                    : new InputStreamReader(conn.getErrorStream(), StandardCharsets.UTF_8);

            StringBuilder response = new StringBuilder();
            try (BufferedReader br = new BufferedReader(reader)) {
                String line;
                while ((line = br.readLine()) != null) {
                    response.append(line.trim());
                }
            }
            return response.toString();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    // 2. Hàm lấy giá trị từ chuỗi JSON
    private String extractJsonValue(String json, String key) {
        try {
            String search = "\"" + key + "\":";
            int start = json.indexOf(search);
            if (start == -1) return "0";
            start += search.length();
            while (json.charAt(start) == ' ' || json.charAt(start) == '"') start++;
            int end = start;
            while (end < json.length() && json.charAt(end) != '"' && json.charAt(end) != ',' && json.charAt(end) != '}') {
                end++;
            }
            return json.substring(start, end).trim();
        } catch (Exception e) { return "0"; }
    }

    // 3. Hàm tách danh sách JSON (Để đổ vào bảng)
    private List<String[]> parseJsonArray(String json, String arrayKey, String[] fields) {
        List<String[]> list = new ArrayList<>();
        try {
            int arrayStart = json.indexOf("\"" + arrayKey + "\":[");
            if (arrayStart == -1) return list;
            String content = json.substring(arrayStart + arrayKey.length() + 4);
            int arrayEnd = content.lastIndexOf("]");
            if (arrayEnd == -1) return list;
            content = content.substring(0, arrayEnd);
            String[] objects = content.split("\\},\\{");
            for (String obj : objects) {
                String[] row = new String[fields.length];
                for (int i = 0; i < fields.length; i++) {
                    row[i] = extractJsonValue(obj, fields[i]);
                }
                list.add(row);
            }
        } catch (Exception e) { }
        return list;
    }

    // 4. Hàm tạo Menu Chuột Phải (Sửa/Xóa)
    private void addContextMenu(JTable table, Runnable editAction, Runnable deleteAction) {
        JPopupMenu popupMenu = new JPopupMenu();
        JMenuItem editItem = new JMenuItem("Sửa thông tin / Chuyển CT");
        JMenuItem deleteItem = new JMenuItem("Xóa dòng này");

        editItem.addActionListener(e -> editAction.run());
        deleteItem.addActionListener(e -> deleteAction.run());

        popupMenu.add(editItem);
        popupMenu.add(deleteItem);

        table.addMouseListener(new MouseAdapter() {
            @Override public void mousePressed(MouseEvent e) { handle(e); }
            @Override public void mouseReleased(MouseEvent e) { handle(e); }
            private void handle(MouseEvent e) {
                if (e.isPopupTrigger()) {
                    JTable source = (JTable) e.getSource();
                    int row = source.rowAtPoint(e.getPoint());
                    if (!source.isRowSelected(row)) source.changeSelection(row, 0, false, false);
                    popupMenu.show(e.getComponent(), e.getX(), e.getY());
                }
            }
        });
    }

    // ==============================================================
    // PHẦN 2: CÁC HÀM LOGIC 
    // ==============================================================

    // Hàm khởi tạo logic chung (Sửa lỗi initCustomLogic)
    private void initCustomLogic() {
        initTableConfigs();    // Cấu hình bảng
        setupButtonEvents();   // Cấu hình nút bấm
    }

    // Hàm chuyển màn hình (Sửa lỗi switchScreen)
    private void switchScreen(String cardName) {
        CardLayout cl = (CardLayout) (contentPanel.getLayout());
        cl.show(contentPanel, cardName);
    }

    // Hàm load Dashboard (Sửa lỗi loadDashboardData)
    private void loadDashboardData() {
        new Thread(() -> {
            String cSite = extractJsonValue(sendRequest("/admin/CountSite", "GET", null), "totalCount");
            String cCust = extractJsonValue(sendRequest("/admin/CountCustomer", "GET", null), "totalCount");
            String cStaff = extractJsonValue(sendRequest("/admin/CountStaff", "GET", null), "totalCount");

            SwingUtilities.invokeLater(() -> {
                DefaultTableModel model = (DefaultTableModel) tblDashboardReport.getModel();
                model.setRowCount(0);
                model.addRow(new Object[]{"Tổng Chi Nhánh", cSite});
                model.addRow(new Object[]{"Tổng Khách Hàng", cCust});
                model.addRow(new Object[]{"Tổng Nhân Viên", cStaff});
            });
        }).start();
    }

    // ==============================================================
    // PHẦN 3: CẤU HÌNH UI VÀ SỰ KIỆN
    // ==============================================================

    private void initTableConfigs() {
        // Bảng Dashboard
        tblDashboardReport.setModel(new DefaultTableModel(new Object[][]{}, new String[]{"Danh Mục", "Số Lượng"}));

        // Bảng Chi Nhánh
        tblBranchs.setModel(new DefaultTableModel(new Object[][]{}, new String[]{"Mã CN", "Tên Chi Nhánh", "Thành Phố"}) {
            @Override public boolean isCellEditable(int row, int column) { return false; }
        });
        addContextMenu(tblBranchs, () -> editBranch(), () -> deleteBranch());

        // Bảng Nhân Viên
        tblSaffs.setModel(new DefaultTableModel(new Object[][]{}, new String[]{"Mã NV", "Họ Tên", "Mã CN"}) {
            @Override public boolean isCellEditable(int row, int column) { return false; }
        });
        addContextMenu(tblSaffs, () -> editStaff(), () -> deleteStaff());
        
        // Bảng Câu 1
        tblQuerry.setModel(new DefaultTableModel(new Object[][]{}, new String[]{"Số HĐ Nước", "Tháng", "Năm", "Số Tiền"}) {
        @Override public boolean isCellEditable(int row, int column) { return false; }
    });
    }

    private void setupButtonEvents() {
        // Nút điều hướng Menu
        btnTongQuan.addActionListener(e -> { switchScreen("Dashboard"); loadDashboardData(); });
        btnQuanLyChiNhanh.addActionListener(e -> { switchScreen("QuanLyChiNhanh"); loadBranchData(); });
        btnQuanLyNhanVien.addActionListener(e -> { switchScreen("QuanLyNhanVien"); loadStaffData(); });

        // Nút chức năng
        btnAddBranch.addActionListener(e -> addBranch());
        // Kiểm tra null nếu bạn chưa đặt tên biến này hoặc chưa tạo nút
        if (jButton1 != null) jButton1.addActionListener(e -> addStaff()); 
        
        if (btnSearrch != null) btnSearrch.addActionListener(e -> JOptionPane.showMessageDialog(this, "Tính năng đang phát triển"));
        btnCau1.addActionListener(e -> {
        loadCau1Data();});
    }

    // ==============================================================
    // PHẦN 4: CÁC HÀM XỬ LÝ NGHIỆP VỤ (CRUD)
    // ==============================================================

    // --- CHI NHÁNH ---
    private void loadBranchData() {
        new Thread(() -> {
            String res = sendRequest("/admin/sites", "GET", null);
            List<String[]> data = parseJsonArray(res, "sites", new String[]{"maCN", "tenCN", "thanhpho"});
            SwingUtilities.invokeLater(() -> {
                DefaultTableModel model = (DefaultTableModel) tblBranchs.getModel();
                model.setRowCount(0);
                for (String[] row : data) model.addRow(row);
            });
        }).start();
    }

    private void addBranch() {
        javax.swing.JTextField txtMa = new javax.swing.JTextField();
        javax.swing.JTextField txtTen = new javax.swing.JTextField();
        javax.swing.JComboBox<String> cbCity = new javax.swing.JComboBox<>(new String[]{"TP1", "TP2", "TP3"});
        Object[] msg = {"Mã CN:", txtMa, "Tên CN:", txtTen, "Thành Phố:", cbCity};
        
        if (JOptionPane.showConfirmDialog(this, msg, "Thêm Chi Nhánh", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            String json = String.format("{\"maCN\":\"%s\", \"tenCN\":\"%s\", \"thanhpho\":\"%s\"}", 
                    txtMa.getText(), txtTen.getText(), cbCity.getSelectedItem());
            if (sendRequest("/admin/addsite", "POST", json).contains("true")) {
                JOptionPane.showMessageDialog(this, "Thêm thành công!");
                loadBranchData();
            } else JOptionPane.showMessageDialog(this, "Thất bại!");
        }
    }

    private void deleteBranch() {
        int row = tblBranchs.getSelectedRow();
        if (row == -1) return;
        String maCN = tblBranchs.getValueAt(row, 0).toString();
        if (JOptionPane.showConfirmDialog(this, "Xóa chi nhánh " + maCN + "?", "Cảnh báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            String res = sendRequest("/admin/sites/" + maCN, "DELETE", null);
            if (res.contains("true")) {
                JOptionPane.showMessageDialog(this, "Đã xóa!");
                loadBranchData();
            } else JOptionPane.showMessageDialog(this, "Lỗi: " + extractJsonValue(res, "message"));
        }
    }

    private void editBranch() {
        int row = tblBranchs.getSelectedRow();
        if (row == -1) return;
        String maCN = tblBranchs.getValueAt(row, 0).toString();
        String tenOld = tblBranchs.getValueAt(row, 1).toString();
        String cityOld = tblBranchs.getValueAt(row, 2).toString(); 

        String newName = JOptionPane.showInputDialog(this, "Đổi tên chi nhánh " + maCN + ":", tenOld);
        if (newName != null) {
            String json = String.format("{\"tenCN\":\"%s\", \"thanhpho\":\"%s\"}", newName, cityOld);
            if (sendRequest("/admin/sites/" + maCN, "PUT", json).contains("true")) {
                JOptionPane.showMessageDialog(this, "Đã cập nhật!");
                loadBranchData();
            } else JOptionPane.showMessageDialog(this, "Lỗi cập nhật!");
        }
    }

    // --- NHÂN VIÊN ---
    private void loadStaffData() {
        new Thread(() -> {
            String res = sendRequest("/admin/staffs", "GET", null);
            List<String[]> data = parseJsonArray(res, "staffs", new String[]{"maNV", "hoten", "maCN"});
            SwingUtilities.invokeLater(() -> {
                DefaultTableModel model = (DefaultTableModel) tblSaffs.getModel();
                model.setRowCount(0);
                for (String[] row : data) model.addRow(new Object[]{row[0], row[1], row[2]});
            });
        }).start();
    }

    private void addStaff() {
        javax.swing.JTextField txtMa = new javax.swing.JTextField();
        javax.swing.JTextField txtTen = new javax.swing.JTextField();
        javax.swing.JTextField txtEmail = new javax.swing.JTextField();
        javax.swing.JPasswordField txtPass = new javax.swing.JPasswordField();
        javax.swing.JTextField txtMaCN = new javax.swing.JTextField();
        javax.swing.JComboBox<String> cbCity = new javax.swing.JComboBox<>(new String[]{"TP1", "TP2", "TP3"});
        
        Object[] msg = {"Mã NV:", txtMa, "Họ Tên:", txtTen, "Email:", txtEmail, "Mật khẩu:", txtPass, "Mã CN:", txtMaCN, "Thành phố:", cbCity};
        
        if (JOptionPane.showConfirmDialog(this, msg, "Thêm Nhân Viên", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            String json = String.format("{\"maNV\":\"%s\",\"hoten\":\"%s\",\"Email\":\"%s\",\"Password\":\"%s\",\"maCN\":\"%s\",\"thanhpho\":\"%s\"}", 
                    txtMa.getText(), txtTen.getText(), txtEmail.getText(), new String(txtPass.getPassword()), txtMaCN.getText(), cbCity.getSelectedItem());
            if (sendRequest("/admin/staffs", "POST", json).contains("true")) {
                JOptionPane.showMessageDialog(this, "Thêm NV thành công!");
                loadStaffData();
            } else JOptionPane.showMessageDialog(this, "Thêm thất bại!");
        }
    }

    private void deleteStaff() {
        int row = tblSaffs.getSelectedRow();
        if (row == -1) return;
        String maNV = tblSaffs.getValueAt(row, 0).toString();
        if (JOptionPane.showConfirmDialog(this, "Xóa nhân viên " + maNV + "?", "Cảnh báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            if (sendRequest("/admin/staffs/" + maNV, "DELETE", null).contains("true")) {
                JOptionPane.showMessageDialog(this, "Đã xóa!");
                loadStaffData();
            } else JOptionPane.showMessageDialog(this, "Xóa thất bại!");
        }
    }

    private void editStaff() {
        int row = tblSaffs.getSelectedRow();
        if (row == -1) return;
        String maNV = tblSaffs.getValueAt(row, 0).toString();
        String tenCu = tblSaffs.getValueAt(row, 1).toString();
        String cnCu = tblSaffs.getValueAt(row, 2).toString();

        javax.swing.JTextField txtTen = new javax.swing.JTextField(tenCu);
        javax.swing.JTextField txtCN = new javax.swing.JTextField(cnCu);
        javax.swing.JComboBox<String> cbCity = new javax.swing.JComboBox<>(new String[]{"TP1", "TP2", "TP3"});
        
        Object[] msg = {"Mã NV (Không sửa): " + maNV, "Họ Tên:", txtTen, "Chuyển tới Mã CN:", txtCN, "Thuộc TP:", cbCity};
        
        if (JOptionPane.showConfirmDialog(this, msg, "Sửa / Chuyển Công Tác", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            String json = String.format("{\"hoten\":\"%s\", \"maCN\":\"%s\", \"thanhpho\":\"%s\"}", 
                    txtTen.getText(), txtCN.getText(), cbCity.getSelectedItem());
            String res = sendRequest("/admin/staffs/" + maNV, "PUT", json);
            if (res.contains("true")) {
                JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
                loadStaffData();
            } else JOptionPane.showMessageDialog(this, "Lỗi: " + extractJsonValue(res, "message"));
        }
    }
    
    // Trong AdminDashboardFrame.java
//  Hàm load dữ liệu cho Truy vấn Câu 1
private void loadCau1Data() {
    new Thread(() -> {
        // 1. Lấy tham số truy vấn từ các trường nhập liệu
        String maNV = txtMNV.getText().trim();
        String maKH = txtMKH.getText().trim();

        if (maNV.isEmpty() || maKH.isEmpty()) {
            SwingUtilities.invokeLater(() -> JOptionPane.showMessageDialog(this, "Vui lòng nhập Mã Nhân Viên và Mã Khách Hàng.", "Lỗi nhập liệu", JOptionPane.WARNING_MESSAGE));
            return;
        }

        // 2. Chuẩn bị Endpoint với Query Parameters
        String endpoint = String.format("/api/cau1?maNV=%s&maKH=%s", maNV, maKH);
        
        // 3. Gọi API
        String res = sendRequest(endpoint, "GET", null);
        
        // Kiểm tra lỗi trả về từ API
        if (res == null || res.contains("\"success\":false")) {
             String message = extractJsonValue(res, "message");
             SwingUtilities.invokeLater(() -> JOptionPane.showMessageDialog(this, "Truy vấn thất bại: " + message, "Lỗi API", JOptionPane.ERROR_MESSAGE));
             return;
        }

        // 4. Phân tích kết quả JSON
        String[] fields = {"soHDN", "thang", "nam", "soTien"};
        List<String[]> data = parseJsonArray(res, "hoatong", fields);

        // 5. Cập nhật giao diện (trên EDT)
        SwingUtilities.invokeLater(() -> {
            DefaultTableModel model = (DefaultTableModel) tblQuerry.getModel();
            model.setRowCount(0); // Xóa dữ liệu cũ
            for (String[] row : data) model.addRow(row);
            
            if (data.isEmpty()) {
                 JOptionPane.showMessageDialog(this, "Không tìm thấy hóa đơn nào.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
        });
    }).start();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel branchManagementPanel;
    private javax.swing.JButton btnAddBranch;
    private javax.swing.JButton btnAdddSaff;
    private javax.swing.JButton btnCau1;
    private javax.swing.JButton btnQuanLyChiNhanh;
    private javax.swing.JButton btnQuanLyNhanVien;
    private javax.swing.JButton btnSearrch;
    private javax.swing.JButton btnTongQuan;
    private javax.swing.JButton btnTruyVan;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel dashboardScreenPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel queryPanel;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JPanel staffManagementPanel;
    private javax.swing.JTable tblBranchs;
    private javax.swing.JTable tblDashboardReport;
    private javax.swing.JTable tblQuerry;
    private javax.swing.JTable tblSaffs;
    private javax.swing.JTextField txtMKH;
    private javax.swing.JTextField txtMNV;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSearchSaff;
    // End of variables declaration//GEN-END:variables
}
