/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package csdlpt;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import javax.swing.JOptionPane;

/**
 *
 * @author 123de
 */
public class LoginFrame extends javax.swing.JFrame {

    /** Creates new form LoginFrame */
    public LoginFrame() {
        initComponents();
    }
    
    
    
    private String extractJsonValue(String json, String key) {
    if (json == null) return "";
    try {
        String searchKey = "\"" + key + "\":";
        int startIndex = json.indexOf(searchKey);
        if (startIndex == -1) return ""; // Không tìm thấy key

        startIndex += searchKey.length();
        
        // Bỏ qua khoảng trắng
        while (startIndex < json.length() && json.charAt(startIndex) == ' ') {
            startIndex++;
        }
        
        int endIndex;
        boolean isString = false;
        
        // Nếu giá trị bắt đầu bằng dấu ngoặc kép, đây là chuỗi (String)
        if (startIndex < json.length() && json.charAt(startIndex) == '\"') {
            isString = true;
            startIndex++; // Bỏ qua dấu ngoặc kép mở đầu
            endIndex = json.indexOf("\"", startIndex);
        } else {
            // Đây là số, boolean, hoặc null
            endIndex = json.indexOf(",", startIndex);
            if (endIndex == -1) endIndex = json.indexOf("}", startIndex);
            if (endIndex == -1) endIndex = json.length(); // Trường hợp là key cuối cùng
        }

        if (endIndex == -1 || endIndex < startIndex) return ""; // Lỗi cú pháp
        
        String value = json.substring(startIndex, endIndex).trim();
        
        // Nếu nó không phải là chuỗi (isString=false) nhưng lại có dấu ngoặc kép thừa, loại bỏ.
        // Tuy nhiên, với logic mới này, phần lớn dấu ngoặc kép đã được xử lý.
        
        return value;
    } catch (Exception e) {
        System.err.println("Lỗi trích xuất JSON cho key " + key + ": " + e.getMessage());
        return "";
    }
}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        txtAccount = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        btnRegister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 48)); // NOI18N
        jLabel1.setText("Login");

        btnLogin.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        btnLogin.setText("Đăng Nhập");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        txtAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccountActionPerformed(evt);
            }
        });

        btnRegister.setText("Đăng Ký");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegister)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccountActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String email = txtAccount.getText().trim();
        String password = new String(txtPass.getPassword()).trim();

        if (email.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập email và mật khẩu!");
            return;
        }

        try {
            // 1. Cấu hình URL (Đảm bảo đúng Port server Node.js đang chạy, ví dụ 9999)
                URL url = new URL("http://127.0.0.1:9999/login");            
            HttpURLConnection conn = (HttpURLConnection) url.openConnection();
            conn.setRequestMethod("POST");
            conn.setRequestProperty("Content-Type", "application/json");
conn.setRequestProperty("Charset", "UTF-8");
            conn.setRequestProperty("Accept", "application/json");
            conn.setDoOutput(true);

            String jsonInputString = "{\"email\": \"" + email + "\", \"password\": \"" + password + "\"}";
            // 2. Gửi Request
            try (OutputStream os = conn.getOutputStream()) {
                byte[] input = jsonInputString.getBytes(StandardCharsets.UTF_8);
                os.write(input, 0, input.length);
            }

            // 3. Nhận Response
            int responseCode = conn.getResponseCode();
            StringBuilder response = new StringBuilder();
            
            InputStreamReader reader;
            if (responseCode == 200) {
                reader = new InputStreamReader(conn.getInputStream(), StandardCharsets.UTF_8);
            } else {
                reader = new InputStreamReader(conn.getErrorStream(), StandardCharsets.UTF_8);
            }
            
            try (BufferedReader br = new BufferedReader(reader)) {
                String line;
                while ((line = br.readLine()) != null) {
                    response.append(line.trim());
                }
            }

            String responseBody = response.toString();
            System.out.println("Server Response: " + responseBody);

            // 4. XỬ LÝ PHÂN QUYỀN (LOGIC QUAN TRỌNG NHẤT)
     if (responseCode == 200) {
                String role = extractJsonValue(responseBody, "role");
                String token = extractJsonValue(responseBody, "token");
                
                // BẮT ĐẦU LOGIC LẤY MÃ NV ĐA TẦNG
                String maNV = "";
                
                // Thử lấy key "id" (theo JWT)
                if (maNV.isEmpty()) maNV = extractJsonValue(responseBody, "id");
                
                // Thử lấy key "MaNV" (theo tên cột SQL)
                if (maNV.isEmpty()) maNV = extractJsonValue(responseBody, "MaNV"); 
                
                // Thử lấy key "maNV" (viết thường)
                if (maNV.isEmpty()) maNV = extractJsonValue(responseBody, "maNV"); 
                
                // BỔ SUNG: Kiểm tra cuối cùng, nếu vẫn rỗng, thử key "ID" (phòng trường hợp viết hoa hoàn toàn)
                if (maNV.isEmpty()) maNV = extractJsonValue(responseBody, "ID"); 

                // Lỗi chỉ xảy ra khi maNV bị trích xuất là rỗng.
                if (maNV.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Đăng nhập thành công, nhưng không lấy được Mã Nhân Viên (ID) để tải dữ liệu.", "Lỗi Dữ liệu", JOptionPane.ERROR_MESSAGE);
                    this.dispose(); 
                    return; 
                }

                // Nếu thành công, tiếp tục mở form
                JOptionPane.showMessageDialog(this, "Đăng nhập thành công! Vai trò: " + role);
                this.dispose(); 

                if (role.equalsIgnoreCase("admin") || role.equalsIgnoreCase("quanly")) {
                    new AdminDashboardFrame(token).setVisible(true);
                } else {
                    // Truyền token và maNV đã lấy được (ví dụ: NV7)
                    new csdlpt.EmployeeAppFrame(token, maNV).setVisible(true);
                }
                
            } else {
                String message = extractJsonValue(responseBody, "message");
                JOptionPane.showMessageDialog(this, "Đăng nhập thất bại: " + message);
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi kết nối Server: " + e.getMessage());
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtAccount;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables

}
